В файле <i>orders</i> представлена информация о заказах в онлайн-магазине.
```
OrderID - ID Заказа,
UserID - ID клиента,
OrderTime - время заказа,
items - список элементов в заказе, каждый элемент описан словарем:
    ItemID  - ID продукта, 
    price - цена единицы товара, 
    quantity - количество единиц товара в заказе
```
В файле <i>categories</i> представлена информация о категории товаров.
```
ItemID - ID продукта,
Category - категория продукта,
ParentCategory - более крупная категория продукта
```

## Анализ логов продуктового магазина

Представьте, что вы работаете аналитиком онлайн-магазина и ваша цель - повысить GMV (суммарную выручку от продажи товаров). Для этого вы хотите провести ряд исследований и придумать какие-то меры для увеличения выручки.

* Определите, какого числа было сделано больше всего заказов?
* Найдите топ-3 ParentCategory по GMV (суммарная выручка, которую принесла продажа товаров этой категории)
* Напишите функцию, которая принимает на вход OrderID и рекомендует ItemID продукта для корзины этого заказа. Проверьте работу этой функции.

In [1]:
import pandas as pd

In [ ]:
# Для скачивания файлов из репозитория в Colab 
# !wget https://github.com/da-python/new-modul-python/blob/main/Lesson4/hometask/data/categories.csv -P data
# !wget https://github.com/da-python/new-modul-python/blob/main/Lesson4/hometask/data/orders.json -P data

In [52]:
categories = pd.read_csv('data/categories.csv')
orders = pd.read_json('data/orders.json')

In [53]:
categories.head()

    ItemID                 Category  ParentCategory
0  1000002  Сладости для диабетиков        Сладости
1  1000046                     Вода         Напитки
2  1000048  Сладости для диабетиков        Сладости
3  1000049                     Вода         Напитки
4  1000061                   Фрукты  Овощи и фрукты

In [54]:
orders.head()

,OrderID,UserID,OrderTime,items,Date
0,90659865,1.609460e+18,2021-01-01 03:51:42,"[{'ItemID': '413736', 'price': 36.72, 'quantit...",2021-01-01
1,90622054,2.499293e+18,2021-01-01 04:13:13,"[{'ItemID': '961454', 'price': 179.9, 'quantit...",2021-01-01
2,90659952,3.945866e+17,2021-01-01 05:48:53,"[{'ItemID': '306553', 'price': 101.9, 'quantit...",2021-01-01
3,89765281,5.412765e+18,2021-01-01 08:33:41,"[{'ItemID': '979703', 'price': 99.9, 'quantity...",2021-01-01
4,90582308,6.380061e+18,2021-01-01 09:55:35,"[{'ItemID': '303765', 'price': 44.9, 'quantity...",2021-01-01

In [41]:
orders[orders.OrderID == 90659865]['items'].tolist()

[[{'ItemID': '413736', 'price': 36.72, 'quantity': 2},
  {'ItemID': '523171', 'price': 90.32, 'quantity': 1},
  {'ItemID': '452831', 'price': 223.11, 'quantity': 1},
  {'ItemID': '303673', 'price': 59.9, 'quantity': 7},
  {'ItemID': '318193', 'price': 319.91, 'quantity': 2},
  {'ItemID': '345578', 'price': 159.92, 'quantity': 1},
  {'ItemID': '316140', 'price': 135.92, 'quantity': 2},
  {'ItemID': '444061', 'price': 291.12, 'quantity': 2},
  {'ItemID': '500982', 'price': 36.72, 'quantity': 3},
  {'ItemID': '303682', 'price': 63.26, 'quantity': 2},
  {'ItemID': '308467', 'price': 35.11, 'quantity': 3},
  {'ItemID': '312673', 'price': 289.9, 'quantity': 1},
  {'ItemID': '429288', 'price': 179.9, 'quantity': 1},
  {'ItemID': '306876', 'price': 29.9, 'quantity': 1},
  {'ItemID': '306843', 'price': 75.12, 'quantity': 1},
  {'ItemID': '521581', 'price': 79.92, 'quantity': 1},
  {'ItemID': '303669', 'price': 116.87, 'quantity': 1},
  {'ItemID': '313776', 'price': 99.9, 'quantity': 1},
  {'ItemID': '521656', 'price': 119.9, 'quantity': 1},
  {'ItemID': '315179', 'price': 127.92, 'quantity': 1},
  {'ItemID': '1003647', 'price': 39.92, 'quantity': 6},
  {'ItemID': '363466', 'price': 111.12, 'quantity': 1}]]

In [6]:
categories.shape

(35030, 3)

In [7]:
categories.Category.nunique()

493

In [8]:
categories.ParentCategory.nunique()

17

In [9]:
categories.ItemID.nunique()

35030

In [10]:
orders.shape

(40375, 5)

In [11]:
orders.UserID.nunique()

14778

In [ ]:
orders.items

In [16]:
orders['items'][0]

[{'ItemID': '413736', 'price': 36.72, 'quantity': 2},
 {'ItemID': '523171', 'price': 90.32, 'quantity': 1},
 {'ItemID': '452831', 'price': 223.11, 'quantity': 1},
 {'ItemID': '303673', 'price': 59.9, 'quantity': 7},
 {'ItemID': '318193', 'price': 319.91, 'quantity': 2},
 {'ItemID': '345578', 'price': 159.92, 'quantity': 1},
 {'ItemID': '316140', 'price': 135.92, 'quantity': 2},
 {'ItemID': '444061', 'price': 291.12, 'quantity': 2},
 {'ItemID': '500982', 'price': 36.72, 'quantity': 3},
 {'ItemID': '303682', 'price': 63.26, 'quantity': 2},
 {'ItemID': '308467', 'price': 35.11, 'quantity': 3},
 {'ItemID': '312673', 'price': 289.9, 'quantity': 1},
 {'ItemID': '429288', 'price': 179.9, 'quantity': 1},
 {'ItemID': '306876', 'price': 29.9, 'quantity': 1},
 {'ItemID': '306843', 'price': 75.12, 'quantity': 1},
 {'ItemID': '521581', 'price': 79.92, 'quantity': 1},
 {'ItemID': '303669', 'price': 116.87, 'quantity': 1},
 {'ItemID': '313776', 'price': 99.9, 'quantity': 1},
 {'ItemID': '521656', 'price': 119.9, 'quantity': 1},
 {'ItemID': '315179', 'price': 127.92, 'quantity': 1},
 {'ItemID': '1003647', 'price': 39.92, 'quantity': 6},
 {'ItemID': '363466', 'price': 111.12, 'quantity': 1}]

In [18]:
orders['items'][0][0].get('ItemID')

'413736'

In [19]:
orders['items'][0][0].get('price')

36.72

In [20]:
orders['items'][0][0].get('quantity')

2

In [21]:
df = pd.DataFrame([])

In [22]:
[
    [2,2],
    [3,3],
    [4,4]
]

[[2, 2], [3, 3], [4, 4]]

In [24]:
pd.DataFrame([
    [2,2],
    [3,3],
    [4,4]
], columns=['col1', 'col2'])

   col1  col2
0     2     2
1     3     3
2     4     4

In [25]:
pd.DataFrame({
    'col1':[1,1,1,1],
    'col2':[3,3,3,3]

})

   col1  col2
0     1     3
1     1     3
2     1     3
3     1     3

In [26]:
pd.DataFrame({
    'item_id':[1,1,1,1],
    'price':[1,1,1,1],
    'quantity':[3,3,3,3]

})

   item_id  price  quantity
0        1      1         3
1        1      1         3
2        1      1         3
3        1      1         3

In [29]:
a = pd.DataFrame({
    'item_id':[1,2,1,2],
    'price_x':[1,1,1,1],
    'quantity_x':[3,3,3,3]

})

In [30]:
b = pd.DataFrame({
    'item_id':[2,1,2,1],
    'price_y':[1,1,1,1],
    'quantity_y':[3,3,3,3]

})

In [32]:
pd.merge(a,b, on='item_id', how='inner')

   item_id  price_x  quantity_x  price_y  quantity_y
0        1        1           3        1           3
1        1        1           3        1           3
2        2        1           3        1           3
3        2        1           3        1           3
4        1        1           3        1           3
5        1        1           3        1           3
6        2        1           3        1           3
7        2        1           3        1           3

In [36]:
a.set_index('item_id')

         price_x  quantity_x
item_id
1              1           3
2              1           3
1              1           3
2              1           3

In [37]:
b.set_index('item_id')

         price_y  quantity_y
item_id
2              1           3
1              1           3
2              1           3
1              1           3

In [38]:
pd.concat([a.set_index('item_id'), b.set_index('item_id')], axis=0)

         price_x  quantity_x  price_y  quantity_y
item_id
1            1.0         3.0      NaN         NaN
2            1.0         3.0      NaN         NaN
1            1.0         3.0      NaN         NaN
2            1.0         3.0      NaN         NaN
2            NaN         NaN      1.0         3.0
1            NaN         NaN      1.0         3.0
2            NaN         NaN      1.0         3.0
1            NaN         NaN      1.0         3.0